#!/usr/bin/env bash
#MISE description="▶  Start dev server (watch mode) + full dev stack (db + redis)"
docker compose --profile dev-stack up -d --remove-orphans
uv run alembic -c resources/alembic.ini upgrade head
uv run uvicorn server:app --app-dir resources --reload --host 0.0.0.0 --port 8080
