apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://user-service-prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
